Fixes #178: Improved error handling for maps and keys options
neo4j-contrib/neo4j-spark-connector pull request #184
Opened 2020-09-15 10:59 UTC by utnaf

Fixes #178 

Details in the issue. 

With this changes, the following scenario:

```scala
val musicDf = Seq(
      (1, 12, "John Henry Bonham", "Drums"),
      (2, 19, "John Mayer", "Guitar"),
      (3, 32, "John Scofield", "Guitar"),
      (4, 15, "John Butler", "Guitar")
    ).toDF("id", "experience", "name", "instrument")

    musicDf.write
        .format(classOf[DataSource].getName)
        .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
        .option("relationship", "PLAYS")
        .option("relationship.source.save.mode", "Overwrite")
        .option("relationship.target.save.mode", "Overwrite")
        .option("relationship.save.strategy", "keys")
        .option("relationship.source.labels", ":Musician")
        .option("relationship.source.node.keys", "musician_name:name,another_name:name") // <-- wrong
        .option("relationship.target.labels", ":Instrument")
        .option("relationship.target.node.keys", "instrument_name:name") // <-- wrong
        .save()
```

will produce the following error:

```
Write failed due to the following errors:
 - Schema is missing instrument_name from option `relationship.target.node.keys`
 - Schema is missing musician_name, another_name from option `relationship.source.node.keys`

The option key and value might be inverted.
```

More examples in the new tests.

Minor issues fixed in the PR:
- Jar name is wrong due to a misspelled variable in pom.xml

2020-09-15 17:39 UTC, moxious approved these changes

2020-09-17 07:54 UTC, conker84 requested changes

2020-09-17 07:54 UTC, conker84 commented on src/main/scala/org/neo4j/spark/service/MappingService.scala
> +  private def keysStrategyConsumer(schema: StructType): MappingBiConsumer = new MappingBiConsumer {
is `(schema: StructType)` necessary?
Can we do this?
```suggestion
  private val keysStrategyConsumer = new MappingBiConsumer {
```

2020-09-17 07:54 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Validations.scala
> +    }
please use the pipe operator `|` with `stripMargin`

2020-09-17 07:54 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Validations.scala
> +    )
can you switch to immutable Map like this?
```scala
val missingFieldsMap = Map(Neo4jOptions.NODE_KEYS -> schema.missingFields(neo4jOptions.nodeMetadata.nodeKeys.keySet),
Neo4jOptions.NODE_PROPS -> schema.missingFields(neo4jOptions.nodeMetadata.nodeProps.keySet)
)
```

2020-09-17 07:54 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala
> +      fields.filter(!structFieldsNames.contains(_))
```suggestion
      fields.filterNot(structFieldsNames.contains(_))
```

2020-09-17 07:54 UTC, conker84 commented on src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala
> +    def missingFields(fields: Set[String]): Set[String] = {
```suggestion
    def getMissingFields(fields: Set[String]): Set[String] = {
```

2020-09-17 07:54 UTC, conker84 commented
@utnaf thank you please look at my comments

2020-09-18 09:36 UTC, conker84 approved these changes

2020-09-18 09:37 UTC, merged

2020-09-18 09:37 UTC, conker84 commented
@utnaf thank you