Fixes #215: rename artifact
neo4j-contrib/neo4j-spark-connector pull request #245
Opened 2020-11-06 13:23 UTC by utnaf

Fixes #215 

Artifact is rename, and correctly generated

![Screenshot 2020-11-06 at 14 22 32](https://user-images.githubusercontent.com/1318539/98370855-874c0e80-203b-11eb-8915-0fb029fb4e71.png)

2020-11-09 11:16 UTC, conker84 requested changes
I would like to have this naming convention since we need to disambiguate scala versions:

* `neo4j-connector-apache-spark-4.0.0-scala-2.11`
* `neo4j-connector-apache-spark-4.0.0-scala-2.12`

@utnaf @moxious WDYT?

2020-11-09 11:16 UTC, conker84 commented on pom.xml
>      <version>4.0.0-alpha</version>
we also need to remove the alpha

2020-11-09 14:33 UTC, conker84 approved these changes, later dismissed

2020-11-10 10:18 UTC, utnaf commented
![Screenshot 2020-11-10 at 11 16 03](https://user-images.githubusercontent.com/1318539/98661004-3e030400-2346-11eb-9d2f-c5345d2977d8.png)

2020-11-10 10:52 UTC, conker84 approved these changes
Thank you @utnaf !

2020-11-10 13:05 UTC, merged