#206: Split current code into common and spark-2.4 modules
neo4j-contrib/neo4j-spark-connector pull request #282
Opened 2021-01-25 16:10 UTC by utnaf

In order to be able to add Spark 3.0 support (#206) we are first opening a PR where we introduce maven modules project structure. Once this is merged we'll add the Spark 3.0 module. 

Current problems:

[ ] When packaged, a `doc` directory is created inside each module (maven frontend plugin's fault)

2021-01-29 14:36 UTC, moxious commented
needs review -- does this keep antora build pipeline in good shape?

2021-01-29 14:50 UTC, moxious commented
@conker84 to review and merge

2021-02-05 12:43 UTC, conker84 approved these changes
@utnaf generally looks good, IDK if makes sense implement my suggestion

2021-02-05 12:48 UTC, conker84 commented
ok for some reason seems that GitHub ignored my comment, I'll post it here:

IDK if makes sense to create a `test-support` module like we did in Streams:
https://github.com/neo4j-contrib/neo4j-streams/tree/4.0/test-support
In order to reuse test classes like `TestUtils` on all classes

2021-02-05 12:51 UTC, conker84 commented
Thinking about it, it makes totally sense there are duplications like `Neo4jContainerExtension` that we want to avoit, please add the `test-support module`

2021-02-05 13:06 UTC, conker84 requested changes
se the comment above

2021-02-08 10:42 UTC, utnaf commented
@conker84 updated

2021-02-08 11:02 UTC, conker84 requested changes
Just that change we need to import it as test package otherwise we'll include them into the distribution artifact.

2021-02-08 11:02 UTC, conker84 commented on spark-2.4/pom.xml
> +            <version>4.0.0</version>
```suggestion
            <version>4.0.0</version>
            <scope>test</test>
```

2021-02-08 14:48 UTC, conker84 commented
LGTM

I'm merging this so we can move forward to `3.0` integration, thank you @utnaf

2021-02-08 14:50 UTC, conker84 approved these changes

2021-02-08 14:50 UTC, merged