Fixes #281: Add Aura integration tests
neo4j-contrib/neo4j-spark-connector pull request #293
Opened 2021-02-18 11:20 UTC by utnaf

Fixes #281 

Add Aura integration tests.

2021-02-18 12:56 UTC, utnaf commented
Regarding #289 I successfully executed some local tests against the Neo4j 4.3 instance that @moxious provided

fyi @conker84

2021-02-25 15:25 UTC, conker84 requested changes
@utnaf please look at my comments

2021-02-25 15:25 UTC, conker84 commented on spark-2.4/src/test/scala/org/neo4j/spark/SparkConnectorAuraTest.scala
> +  val sparkSession = SparkSession.builder()
please create the `sparkSession` after the assume checks in the `BeforeClass` and tear it down in the `AfterClass`

2021-02-25 15:25 UTC, conker84 commented on spark-2.4/src/test/scala/org/neo4j/spark/SparkConnectorAuraTest.scala
> +    if(neo4j.isInstanceOf[Driver]) {
do we need a null check?

2021-02-25 15:25 UTC, conker84 commented on spark-2.4/src/test/scala/org/neo4j/spark/SparkConnectorAuraTest.scala
> +  val sparkSession = SparkSession.builder()
also in spark 3.0

2021-02-25 15:25 UTC, conker84 commented on spark-2.4/src/test/java/org/neo4j/spark/DataSourceReaderTypesTSE.java
> +
can you revert it?

2021-02-26 14:54 UTC, merged