Fixes #299: Add docs for installing the connector
neo4j-contrib/neo4j-spark-connector pull request #305
Opened 2021-03-04 14:34 UTC by utnaf

Fixes #299 

Added docs for connector installation:

- spark packages
- sbt
- maven
- databricks

2021-03-04 15:27 UTC, moxious requested changes

2021-03-04 15:27 UTC, moxious commented on doc/docs/modules/ROOT/pages/quickstart.adoc
> +    <version>4.0.1 </version>
Thanks for doing this PR!

Just change 4.0.1 here to something like ${connector.version} and PR is approved / mergeable.

These docs will age in 6 months and we'll be on a different version, but users will eternally lazy copypasta!

2021-03-05 07:24 UTC, utnaf commented
This also fixes #298

2021-03-05 14:29 UTC, moxious approved these changes

2021-03-05 14:29 UTC, merged