Fixes #323: Node keys are ignored when the field is a map
neo4j-contrib/neo4j-spark-connector pull request #324
Opened 2021-04-13 10:56 UTC by RosarioB

Fixed various issues :

* improved getMissingFields on Neo4jImplicits.scala to support map fields
* fixed createPropsList on Neo4jQueryService.scala

2021-04-15 15:37 UTC, conker84 requested changes
thank you @RosarioB please check my comments

2021-04-15 15:37 UTC, conker84 commented on common/src/main/scala/org/neo4j/spark/service/MappingService.scala
> +        if (options.relationshipMetadata.source.nodeKeys.contains(key) || options.relationshipMetadata.source.nodeKeys.contains(key.quote())) {
Move it to a method `isSourceKey` inside `relationshipMetadata`:

2021-04-15 15:37 UTC, conker84 commented on common/src/main/scala/org/neo4j/spark/service/MappingService.scala
> +        if (options.relationshipMetadata.target.nodeKeys.contains(key) || options.relationshipMetadata.target.nodeKeys.contains(key.quote())) {
same as above, `isTargetKey`

2021-04-15 15:37 UTC, conker84 commented on common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala
> +            """(`.*`)|([^\\.]*)""".r.findFirstIn(s).getOrElse(s).unquote()
it breaks with
```
`foo.bar`.fooBar
```

2021-04-15 15:37 UTC, conker84 commented on common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala
> +            """(`.*`)|([^\\.]*)""".r.findFirstIn(s).getOrElse(s).unquote()
please add a test that manages the use-case ^^^

2021-04-15 15:37 UTC, conker84 commented on spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterNeo4j4xTSE.scala
> +      .option("relationship.source.node.keys", "`source.id`:id")
if this used to work we need to add a *big* note into the documentation, please also review the docs if we use this notation inside it

2021-04-15 15:37 UTC, conker84 commented on spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterTSE.scala
> +    ).toDF("id", "<props>")
add a similar test for a df like this:

```
val df = Seq(
      (1, Map("name" -> "Bonham", "instrument" -> "Drums")),
      (2, Map("name" -> "Mayer", "instrument" -> "Guitar")),
      (3, Map("name" -> "Bon Jovi", "instrument" -> "Voice")),
    ).toDF("id", "my.col")
```

2021-04-15 16:11 UTC, utnaf commented on common/src/main/scala/org/neo4j/spark/util/Neo4jImplicits.scala
> +            """(`.*`)|([^\\.]*)""".r.findFirstIn(s).getOrElse(s).unquote()
This doesn't break, there is already a test case for this

2021-04-15 16:11 UTC, utnaf commented on spark-3/src/test/scala/org/neo4j/spark/DataSourceWriterNeo4j4xTSE.scala
> +      .option("relationship.source.node.keys", "`source.id`:id")
Yep, docs part is missing, I will add it to the todo list for this PR

2021-04-16 06:12 UTC, utnaf commented on common/src/main/scala/org/neo4j/spark/service/MappingService.scala
> +        if (options.relationshipMetadata.source.nodeKeys.contains(key) || options.relationshipMetadata.source.nodeKeys.contains(key.quote())) {
I would move it to "nodemetadata" and create a method "hasKey" and "hasProp", and "getKey" and "getProp"

2021-04-16 07:00 UTC, conker84 commented on common/src/main/scala/org/neo4j/spark/service/MappingService.scala
> +        if (options.relationshipMetadata.source.nodeKeys.contains(key) || options.relationshipMetadata.source.nodeKeys.contains(key.quote())) {
even better

2021-04-22 07:26 UTC, utnaf commented
@conker84 can we close this?

2021-04-22 10:16 UTC, closed without merging