[Snyk] Upgrade org.scala-lang:scala-reflect from 2.13.9 to 2.13.11
neo4j-contrib/neo4j-spark-connector pull request #542
Opened 2023-08-25 03:51 UTC by fbiville

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade org.scala-lang:scala-reflect from 2.13.9 to 2.13.11.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **4 versions** ahead of your current version.
- The recommended version was released **3 months ago**, on 2023-06-02.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiI2NWE5ZDBlNi1kMDI0LTQ2YjUtOWQyOC0wNjM2MzkyNTA2YjkiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6IjY1YTlkMGU2LWQwMjQtNDZiNS05ZDI4LTA2MzYzOTI1MDZiOSJ9fQ==" width="0" height="0"/>

🧐 [View latest project report](https://app.snyk.io/org/connectors-0mk/project/d88fe56e-b8a2-44d7-bb0e-2c0a16edb4bb?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/connectors-0mk/project/d88fe56e-b8a2-44d7-bb0e-2c0a16edb4bb/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/connectors-0mk/project/d88fe56e-b8a2-44d7-bb0e-2c0a16edb4bb/settings/integration?pkg&#x3D;org.scala-lang:scala-reflect&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

2023-08-25 09:01 UTC, conker84 requested changes

2023-08-25 09:01 UTC, conker84 commented on pom.xml
> -                <scala.version>2.12.17</scala.version>
No

2023-08-25 09:01 UTC, conker84 commented on pom.xml
> -                <scala.version>2.13.9</scala.version>
Ok

2023-09-11 14:23 UTC, ali-ince approved these changes

2023-09-11 15:27 UTC, merged